# @package network

num_prompts: 16
side_reduction_ratio: 8
prompt_reduction_ratio: 1
prompt_norm: true
prompt_proj: false

layers_to_extract: 6-11

token_ratio: 0.2
token_imp: "global"

side_input_size: 128
pretrained_path: "google/vit-base-patch16-384"

input_size: 384
backbone_input_size: 224
vit_feature_branch: [0, 2]

fold_id: 0
drop_path_rate: 0.2
prototype_momentum: 0.99
tta_lr: 0.001
tta_lambda_conf: 1.0
