# @package dataset
name: "customized"

# ------------------------------------------------------------------
# Paths & Directories
# ------------------------------------------------------------------
data_path: "/content/GeoSpec_FPT/dataset"
preload_path: "/content/GeoSpec_FPT/preload_dataset"
save_path: "/content/GeoSpec_FPT/save"
output_dir:  "/content/GeoSpec_FPT/output"

# ------------------------------------------------------------------
# Image & Dataset Properties
# ------------------------------------------------------------------
input_size: 512
image_channels: 3
num_classes: 2
mean: [0.6105489, 0.6105489, 0.6105489]
std: [0.25847816, 0.25847816, 0.25847816]

# ------------------------------------------------------------------
# Splits & Preload Directories
# ------------------------------------------------------------------
train_split: "train"
val_split: "val"
test_split: "test"
train_preload_dir: ""
val_preload_dir: ""
test_preload_dir: ""

# ------------------------------------------------------------------
# Domain & Augmentation
# ------------------------------------------------------------------
domain_metadata_path: ""
num_domains: 0
use_augmentation: false
data_augmentation_args: []
